In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import math
import warnings
warnings.filterwarnings('ignore') # Hides warning
warnings.filterwarnings("ignore", category=DeprecationWarning)
warnings.filterwarnings("ignore",category=UserWarning)
sns.set_style("whitegrid") # Plotting style
%matplotlib inline # Plots show up in notebook
np.random.seed(7) # seeding random number generator

UsageError: unrecognized arguments: # Plots show up in notebook


In [3]:
df= pd.read_csv("E:/Amzon Product Review/Processing dataset/review_processing_file.csv")

In [4]:
df.head()

Unnamed: 0                    id  \
0           0  AVqkIhwDv8e3D1O-lebb   
1           1  AVqkIhwDv8e3D1O-lebb   
2           2  AVqkIhwDv8e3D1O-lebb   
3           3  AVqkIhwDv8e3D1O-lebb   
4           4  AVqkIhwDv8e3D1O-lebb   

                                        reviews.text  Sentiment  \
0  This product so far has not disappointed. My c...        1.0   
1  great for beginner or experienced person. Boug...        1.0   
2  Inexpensive tablet for him to use and learn on...        1.0   
3  I've had my Fire HD 8 two weeks now and I love...        1.0   
4  I bought this for my grand daughter when she c...        1.0   

                                        clean_review  \
0  ['this', 'product', 'so', 'far', 'has', 'not',...   
1  ['great', 'for', 'beginner', 'or', 'experience...   
2  ['inexpensive', 'tablet', 'for', 'him', 'to', ...   
3  ['have', 'had', 'my', 'fire', 'hd', 'two', 'we...   
4  ['bought', 'this', 'for', 'my', 'grand', 'daug...   

                               review_token_filtered  \
0  ['product', 'far', 'disappointed', 'children',...   
1  ['great', 'beginner', 'experienced', 'person',...   
2  ['inexpensive', 'tablet', 'use', 'learn', 'ste...   
3  ['fire', 'hd', 'two', 'weeks', 'love', 'tablet...   
4  ['bought', 'grand', 'daughter', 'comes', 'visi...   

                                      review_stemmed  \
0  product far disappoint children love use like ...   
1     great beginn experienc person bought gift love   
2  inexpens tablet use learn step nabi thrill lea...   
3  fire hd two week love tablet great valu prime ...   
4  bought grand daughter come visit set user ente...   

                                   review_lemmatized  
0  product far disappointed child love use like a...  
1  great beginner experienced person bought gift ...  
2  inexpensive tablet use learn step nabi thrille...  
3  fire hd two week love tablet great value prime...  
4  bought grand daughter come visit set user ente...

In [5]:
df.isnull().sum()

Unnamed: 0               0
id                       0
reviews.text             0
Sentiment                0
clean_review             0
review_token_filtered    0
review_stemmed           3
review_lemmatized        3
dtype: int64

In [6]:

###Drop Nan Values
df=df.dropna()

In [7]:
df.isnull().sum()

Unnamed: 0               0
id                       0
reviews.text             0
Sentiment                0
clean_review             0
review_token_filtered    0
review_stemmed           0
review_lemmatized        0
dtype: int64

In [ ]:
# df.drop(['reviews.text', 'clean_review', 'review_token_filtered'], axis=1, inplace = True)

In [8]:
df.head(2)

Unnamed: 0                    id  \
0           0  AVqkIhwDv8e3D1O-lebb   
1           1  AVqkIhwDv8e3D1O-lebb   

                                        reviews.text  Sentiment  \
0  This product so far has not disappointed. My c...        1.0   
1  great for beginner or experienced person. Boug...        1.0   

                                        clean_review  \
0  ['this', 'product', 'so', 'far', 'has', 'not',...   
1  ['great', 'for', 'beginner', 'or', 'experience...   

                               review_token_filtered  \
0  ['product', 'far', 'disappointed', 'children',...   
1  ['great', 'beginner', 'experienced', 'person',...   

                                      review_stemmed  \
0  product far disappoint children love use like ...   
1     great beginn experienc person bought gift love   

                                   review_lemmatized  
0  product far disappointed child love use like a...  
1  great beginner experienced person bought gift ...

In [9]:
df.drop('Unnamed: 0',inplace=True,axis = 1)

In [12]:
df['review_lemmatized'][1]

'great beginner experienced person bought gift love'

In [13]:
X= df['review_lemmatized']
y= df['Sentiment']

In [14]:
X.shape

(34623,)

In [15]:
y.shape

(34623,)

In [16]:
import tensorflow as tf

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [17]:
### Vocabulary size
voc_size=5000

#### Onehot Representation 

In [18]:
messages=X.copy()

In [20]:
messages.head()

0    product far disappointed child love use like a...
1    great beginner experienced person bought gift ...
2    inexpensive tablet use learn step nabi thrille...
3    fire hd two week love tablet great value prime...
4    bought grand daughter come visit set user ente...
Name: review_lemmatized, dtype: object

#### Embedding Representation

In [25]:
onehot_repr=[one_hot(words,voc_size)for words in messages] 
onehot_repr

[[3033, 4910, 4564, 1861, 1973, 891, 2620, 1695, 1255, 3704, 629, 4217, 4650],
 [1528, 1495, 4186, 4712, 919, 1951, 1973],
 [4557, 3936, 891, 4554, 2438, 1973, 994, 4554, 397, 233],
 [4631,
  2429,
  2202,
  534,
  1973,
  3936,
  1528,
  3050,
  441,
  2784,
  3936,
  35,
  1973,
  428,
  4174,
  2299,
  441,
  629,
  4180,
  271,
  1530,
  1148,
  2555,
  2391,
  2486,
  1134,
  4461,
  1134,
  1742,
  361,
  2326,
  3097,
  661,
  116,
  1148,
  4225,
  254,
  4330,
  4631,
  1050,
  414,
  2821,
  2161,
  823,
  3286,
  3658,
  4102,
  1584,
  2486,
  1186,
  2523,
  2620,
  1655,
  2924,
  2491,
  2633],
 [919,
  2068,
  4109,
  1723,
  3136,
  34,
  4338,
  3669,
  4881,
  3494,
  58,
  247,
  4671,
  2299,
  2119,
  629,
  4262,
  4881,
  2088,
  1973,
  3045,
  154,
  919,
  1566,
  3882,
  2931,
  2268,
  4078,
  3707,
  3936,
  1239,
  661,
  958,
  4401,
  3936,
  2046,
  2210,
  3026,
  4396,
  2459,
  3820,
  7,
  4932,
  1723,
  3677,
  3936,
  3078,
  3372,
  3208,
  313

In [26]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ...  629 4217 4650]
 [   0    0    0 ...  919 1951 1973]
 [   0    0    0 ... 4554  397  233]
 ...
 [2559 3726 2202 ... 1580 2789 2976]
 [4307 1723 1245 ... 4646 4086   58]
 [4951 4725 3564 ... 2468 3019 2210]]


#### LSTM MODEL 

In [32]:
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 20, 40)            200000    
_________________________________________________________________
lstm_1 (LSTM)                (None, 100)               56400     
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 101       
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


#### Bidirectional LSTM Model 

In [47]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Bidirectional
from tensorflow.keras.layers import Dropout

In [48]:
## Creating model
embedding_vector_features=40
model1=Sequential()
model1.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model1.add(Bidirectional(LSTM(100)))
model1.add(Dropout(0.3))
model1.add(Dense(1,activation='sigmoid'))
model1.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model1.summary())

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_5 (Embedding)      (None, 20, 40)            200000    
_________________________________________________________________
bidirectional_1 (Bidirection (None, 200)               112800    
_________________________________________________________________
dropout_3 (Dropout)          (None, 200)               0         
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 201       
Total params: 313,001
Trainable params: 313,001
Non-trainable params: 0
_________________________________________________________________
None


In [49]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [50]:
X_final.shape,y_final.shape

((34623, 20), (34623,))

In [51]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

#### LSTM Model Training 

In [36]:
### Finally Training
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
363/363 [==============================] - 17s 48ms/step - loss: 0.1214 - accuracy: 0.9323 - val_loss: 0.0888 - val_accuracy: 0.9338
Epoch 2/10
363/363 [==============================] - 11s 31ms/step - loss: 0.0949 - accuracy: 0.9330 - val_loss: 0.0759 - val_accuracy: 0.9339
Epoch 3/10
363/363 [==============================] - 11s 29ms/step - loss: 0.0452 - accuracy: 0.9335 - val_loss: 0.0689 - val_accuracy: 0.9332
Epoch 4/10
363/363 [==============================] - 10s 27ms/step - loss: -0.0746 - accuracy: 0.9340 - val_loss: 0.0699 - val_accuracy: 0.9303
Epoch 5/10
363/363 [==============================] - 11s 31ms/step - loss: -0.3186 - accuracy: 0.9347 - val_loss: 0.1289 - val_accuracy: 0.9248
Epoch 6/10
363/363 [==============================] - 12s 33ms/step - loss: -0.7735 - accuracy: 0.9338 - val_loss: 0.1260 - val_accuracy: 0.9273
Epoch 7/10
363/363 [==============================] - 13s 35ms/step - loss: -1.2901 - accuracy: 0.9356 - val_loss: 0.2869 - val_accur

#### Adding Dropout Layer for LSTM

In [37]:
from tensorflow.keras.layers import Dropout
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

#### Performance Metrics And Accuracy for LSTM 

In [38]:
y_pred=model.predict_classes(X_test)

Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).


In [39]:
from sklearn.metrics import confusion_matrix

In [40]:
confusion_matrix(y_test,y_pred)

array([[ 223,  253,    0],
       [4444, 6226,    0],
       [ 136,  144,    0]], dtype=int64)

In [41]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.5644144932609837

#### Model training for the BI-LSTM

In [52]:
### Finally Training
model1.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
363/363 [==============================] - 31s 85ms/step - loss: 0.1243 - accuracy: 0.9311 - val_loss: 0.0800 - val_accuracy: 0.9337
Epoch 2/10
363/363 [==============================] - 23s 63ms/step - loss: 0.0768 - accuracy: 0.9324 - val_loss: 0.0577 - val_accuracy: 0.9338
Epoch 3/10
363/363 [==============================] - 23s 62ms/step - loss: 0.0255 - accuracy: 0.9327 - val_loss: 0.1300 - val_accuracy: 0.9281
Epoch 4/10
363/363 [==============================] - 24s 66ms/step - loss: -0.0427 - accuracy: 0.9308 - val_loss: 0.0765 - val_accuracy: 0.9338
Epoch 5/10
363/363 [==============================] - 27s 75ms/step - loss: -0.2557 - accuracy: 0.9300 - val_loss: 0.0215 - val_accuracy: 0.9332
Epoch 6/10
363/363 [==============================] - 29s 79ms/step - loss: -0.3899 - accuracy: 0.9273 - val_loss: 0.0794 - val_accuracy: 0.9304
Epoch 7/10
363/363 [==============================] - 30s 81ms/step - loss: -0.6865 - accuracy: 0.9251 - val_loss: 0.0406 - val_accur

#### Performance Metrics And Accuracy

In [53]:
y_pred1=model1.predict_classes(X_test)

In [54]:
from sklearn.metrics import confusion_matrix

In [55]:
confusion_matrix(y_test,y_pred1)

array([[    9,   467,     0],
       [   67, 10603,     0],
       [    3,   277,     0]], dtype=int64)

In [56]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred1)

0.9287589707684228

In [57]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred1))

              precision    recall  f1-score   support

         0.0       0.11      0.02      0.03       476
         1.0       0.93      0.99      0.96     10670
         2.0       0.00      0.00      0.00       280

    accuracy                           0.93     11426
   macro avg       0.35      0.34      0.33     11426
weighted avg       0.88      0.93      0.90     11426

